// Typed access to the Florida / Texas location dataset.
//
// The underlying JSON is generated by scripts/build-locations.mjs from public-domain U.S.
// Census data and committed to the repo, so builds never depend on Census being reachable.
// Re-run that script to refresh the vintage or change the city population floor.

import data from '@/lib/data/locations.json';

export type StateSlug = 'florida' | 'texas';
export type StateAbbr = 'FL' | 'TX';

export type StateRef = {
  abbr: StateAbbr;
  slug: StateSlug;
  name: string;
};

export type County = {
  kind: 'county';
  slug: string;
  name: string;
  /** "Miami-Dade County" -> "Miami-Dade", for prose where the suffix reads badly. */
  shortName: string;
  state: StateAbbr;
  stateSlug: StateSlug;
  stateName: string;
  fips: string;
  population: number;
  pop2020: number;
  /** Percentage change 2020 -> 2023; negative for shrinking counties. */
  growthPct: number | null;
  density: number | null;
  /** 1 = most populous county in the state. */
  stateRank: number;
  stateCountyCount: number;
  lat: number | null;
  lng: number | null;
  sqmi: number | null;
  /** Slugs of the dataset's cities in this county, largest first. */
  cities: string[];
};

export type City = {
  kind: 'city';
  slug: string;
  name: string;
  state: StateAbbr;
  stateSlug: StateSlug;
  stateName: string;
  fips: string;
  population: number;
  pop2020: number;
  /** Percentage change 2020 -> 2023; negative for shrinking cities. */
  growthPct: number | null;
  density: number | null;
  /** 1 = most populous city in the state within this dataset. */
  stateRank: number;
  stateCityCount: number;
  countySlug: string | null;
  countyName: string | null;
  lat: number | null;
  lng: number | null;
  sqmi: number | null;
  nearby: { slug: string; miles: number }[];
  /** Nearest market at least 1.6x this city's size — where overflow cases route. */
  nearestLarger: { name: string; slug: string; miles: number } | null;
};

export type Place = County | City;

const DATASET = data as unknown as {
  generatedFrom: string;
  vintage: number;
  minCityPopulation: number;
  states: StateRef[];
  counties: County[];
  cities: City[];
};

export const STATES: StateRef[] = DATASET.states;
export const COUNTIES: County[] = DATASET.counties;
export const CITIES: City[] = DATASET.cities;
export const DATA_VINTAGE = DATASET.vintage;
export const DATA_SOURCE = DATASET.generatedFrom;

const byState = <T extends { stateSlug: StateSlug }>(rows: T[], state: StateSlug) =>
  rows.filter((r) => r.stateSlug === state);

export function getState(slug: string): StateRef | undefined {
  return STATES.find((s) => s.slug === slug);
}

export function countiesIn(state: StateSlug): County[] {
  return byState(COUNTIES, state);
}

export function citiesIn(state: StateSlug): City[] {
  return byState(CITIES, state);
}

export function placesIn(state: StateSlug): Place[] {
  return [...countiesIn(state), ...citiesIn(state)];
}

/**
 * Resolves a place slug within a state. County slugs always end in "-county", so a city can
 * never shadow a county even where the names match (Houston vs Houston County).
 */
export function getPlace(state: string, slug: string): Place | undefined {
  const st = getState(state);
  if (!st) return undefined;
  return (
    countiesIn(st.slug).find((c) => c.slug === slug) ?? citiesIn(st.slug).find((c) => c.slug === slug)
  );
}

export function getCounty(state: StateSlug, slug: string | null): County | undefined {
  if (!slug) return undefined;
  return countiesIn(state).find((c) => c.slug === slug);
}

/** Cities in the same county, largest first, excluding the city itself. */
export function siblingCities(city: City, limit = 6): City[] {
  const county = getCounty(city.stateSlug, city.countySlug);
  if (!county) return [];
  return county.cities
    .filter((slug) => slug !== city.slug)
    .map((slug) => citiesIn(city.stateSlug).find((c) => c.slug === slug))
    .filter((c): c is City => Boolean(c))
    .slice(0, limit);
}

/** Nearest cities within 45 miles, precomputed at dataset build time. */
export function nearbyCities(city: City, limit = 6): { city: City; miles: number }[] {
  return city.nearby
    .slice(0, limit)
    .map((n) => ({ city: citiesIn(city.stateSlug).find((c) => c.slug === n.slug), miles: n.miles }))
    .filter((n): n is { city: City; miles: number } => Boolean(n.city));
}

export function largestCities(state: StateSlug, limit = 12): City[] {
  return citiesIn(state).slice(0, limit);
}

export function largestCounties(state: StateSlug, limit = 12): County[] {
  return countiesIn(state).slice(0, limit);
}

export const isCounty = (place: Place): place is County => place.kind === 'county';
export const isCity = (place: Place): place is City => place.kind === 'city';

/** "Miami, FL" / "Harris County, TX" — the form used in titles and headings. */
export function placeLabel(place: Place): string {
  return `${place.name}, ${place.state}`;
}

/** Population formatted for prose: 2,314,157 -> "2.3 million", 45,120 -> "45,120". */
export function formatPopulation(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)} million`;
  return n.toLocaleString('en-US');
}

/**
 * Rough market-size banding, used to vary page emphasis rather than to state a fact.
 * Large metros get network-depth messaging; small markets get coverage-radius messaging.
 */
export type MarketTier = 'metro' | 'mid' | 'small';

export function marketTier(place: Place): MarketTier {
  if (place.population >= 500_000) return 'metro';
  if (place.population >= 100_000) return 'mid';
  return 'small';
}
